name: qarsspin
description: "A new Flutter project."
publish_to: 'none'

version: 2.4.2+230

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: 10.8.0
  provider: ^6.1.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  cached_network_image: ^3.4.1
  http: ^1.2.2
  image_picker: ^1.0.4
  video_thumbnail: ^0.5.3
  video_player: ^2.8.1
  chewie: ^1.4.0
  panorama_viewer: ^2.0.7
  dropdown_search: ^6.0.2
  flutter_typeahead: ^5.2.0
  image_editor_plus: ^1.0.6
  pro_image_editor: ^11.3.0
  myfatoorah_flutter: ^3.2.3
  timeago: ^3.6.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.3.0
  webview_flutter_wkwebview: ^3.23.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.3
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  sqflite_common_ffi: ^2.3.6
  get_storage:
  flutter_localization:
  flutter_slidable: ^4.0.3
  # cloud_functions: ^6.2.0
  share_plus: ^10.1.4
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher-playstore.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/ic_launcher-playstore.png"
  adaptive_icon_background: "#00FFFFFF"

  web:
    generate: false

  windows:
    generate: false

  macos:
    generate: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/new_svg/
    - assets/images/Dark mode icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/noor_light.ttf
          weight: 300
        - asset: assets/fonts/noor_normal.ttf
          weight: 400
        - asset: assets/fonts/gilroy_medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/noor_bold.ttf
          weight: 700
        - asset: assets/fonts/noor_bold.ttf
          weight: 800